# NumPy Notebook

NumPy is the backbone of scientific computing in Python. It gives us **fast, memory-efficient arrays** and a rich library of math operations.  
Think of a NumPy array as a super-powered list — but all elements share the same data type, and operations run at C-speed!

**Real-world contexts used in this notebook:**
- 🎓 Student exam scores
- 🏏 Cricket match statistics
- 🌡️ City temperature readings
- 📸 Image pixel grids

In [1]:
!pip3 install numpy

In [1]:
import numpy as np

# Helper: print name, shape, ndim, dtype and values
def describe(name, arr):
    print(f"{name}: shape={arr.shape}, ndim={arr.ndim}, dtype={arr.dtype}\n{arr}\n")

## 1. Mental Model: Shapes, Vectorization, Broadcasting

Before writing any code, build a mental picture:
- **1D array** → a single row of values (like one student's marks across subjects)
- **2D array** → a table / matrix (like marks for ALL students across subjects)
- **3D array** → a stack of matrices (like marks for multiple exams, multiple students, multiple subjects)

NumPy's power comes from **vectorized operations** (no Python loops needed) and **broadcasting** (automatically stretching arrays to compatible shapes).

In [2]:
# 🎓 SHAPES: 1D, 2D, 3D
# 1D — marks of ONE student in 3 subjects: Math, Science, English
student_marks = np.array([85, 90, 78])

# 2D — marks of 2 students across 3 subjects (rows=students, cols=subjects)
class_marks = np.array([[85, 90, 78],   # Student A
                         [72, 88, 94]])   # Student B

# 3D — marks from 2 exams, each containing 2 students and 2 subjects
# Think of it as a 'stack' of 2 exam-matrices
all_exams = np.arange(8).reshape(2, 2, 2)  # 2 exams × 2 students × 2 subjects

describe("1D student_marks", student_marks)
describe("2D class_marks",   class_marks)
describe("3D all_exams",     all_exams)

1D student_marks: shape=(3,), ndim=1, dtype=int64
[85 90 78]

2D class_marks: shape=(2, 3), ndim=2, dtype=int64
[[85 90 78]
 [72 88 94]]

3D all_exams: shape=(2, 2, 2), ndim=3, dtype=int64
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [3]:
# 🎓 VECTORIZATION vs Python loop
# Suppose exam scores are out of 50 and we need to convert to percentage (×2)

raw_scores = np.array([40, 35, 45, 38, 50])

# Old way — Python loop (slow for large data)
loop_result = []
for score in raw_scores:
    loop_result.append(score * 2)

# NumPy way — vectorized (one line, C-speed!)
vectorized_result = raw_scores * 2

print(f"Loop result      : {loop_result}")
print(f"Vectorized result: {vectorized_result.tolist()}")
print("Both give the same answer, but NumPy is MUCH faster on large arrays!")

Loop result      : [np.int64(80), np.int64(70), np.int64(90), np.int64(76), np.int64(100)]
Vectorized result: [80, 70, 90, 76, 100]
Both give the same answer, but NumPy is MUCH faster on large arrays!


In [4]:
# 🌡️ BROADCASTING examples
# Daily temperatures (°C) recorded for 2 cities over 3 days
# Row = city, Column = day
temps = np.array([[30, 32, 31],   # City A
                  [28, 27, 29]])   # City B

# Scalar broadcasting: add 5°C to ALL readings (e.g. calibration correction)
temps_corrected = temps + 5

# Row/vector broadcasting: different correction per DAY (not per city)
# correction: Day1 +1, Day2 +2, Day3 +3
day_correction  = np.array([1, 2, 3])
temps_day_adj   = temps + day_correction   # shape (2,3) + shape (3,) → NumPy broadcasts!

describe("temps (2 cities x 3 days)", temps)
print("Scalar (+5 to every element):\n", temps_corrected, "\n")
print("Row broadcasting (+[1,2,3] per day):\n", temps_day_adj)

temps (2 cities x 3 days): shape=(2, 3), ndim=2, dtype=int64
[[30 32 31]
 [28 27 29]]

Scalar (+5 to every element):
 [[35 37 36]
 [33 32 34]] 

Row broadcasting (+[1,2,3] per day):
 [[31 34 34]
 [29 29 32]]


## 2. Universal Syntax Patterns: Creation and Indexing

NumPy gives you many ways to **create** arrays and a powerful **comma-based indexing** syntax.  
Think of `arr[row, col]` as a map coordinate — row first, then column.

| Function | What it does | Analogy |
|---|---|---|
| `np.array(list)` | Converts list to array | Copying from notebook |
| `np.zeros(shape)` | All zeros | Empty answer sheet |
| `np.ones(shape)` | All ones | Full attendance record |
| `np.arange(start,stop,step)` | Evenly spaced integers | Roll numbers 1–100 |
| `np.linspace(start,stop,n)` | Evenly spaced floats | Measuring tape marks |

In [5]:
# 🎓 CREATION helpers with relatable context

# From a list — scores of 5 students in Math
math_scores = np.array([85, 72, 90, 65, 88])

# Zeros — blank score sheet for 3 students × 4 subjects (pre-exam template)
score_sheet = np.zeros((3, 4))

# Ones — attendance matrix: 2 sections × 5 days (everyone present initially)
attendance  = np.ones((2, 5))

# arange — roll numbers for 30 students: 1, 2, 3, ..., 30
roll_numbers = np.arange(1, 31)

# linspace — 6 evenly spaced time points between 0 and 1 hour (for experiment)
time_points  = np.linspace(0, 60, 6)   # 0, 12, 24, 36, 48, 60 minutes

print("Math scores         :", math_scores)
print("Blank score sheet:\n", score_sheet)
print("Attendance matrix:\n", attendance)
print("Roll numbers (1-30) :", roll_numbers)
print("Time points (min)   :", time_points)

Math scores         : [85 72 90 65 88]
Blank score sheet:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Attendance matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Roll numbers (1-30) : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Time points (min)   : [ 0. 12. 24. 36. 48. 60.]


In [6]:
# 🏏 INDEXING with comma syntax
# Scorecard: rows = players (0=Rohit, 1=Virat, 2=Dhoni)
#            cols = innings  (0=Innings1, 1=Innings2, 2=Innings3)
scorecard = np.array([[120, 45, 88],    # Rohit
                       [ 99, 72, 134],   # Virat
                       [ 83, 51,  67]])  # Dhoni

# Single element: Rohit's score in Innings2 → row 0, col 1
rohit_inn2  = scorecard[0, 1]

# Slice: first 2 players, last 2 innings → rows 0-1, cols 1 onwards
top2_last2  = scorecard[0:2, 1:]

# All innings for Dhoni → row 2, all columns
dhoni_all   = scorecard[2, :]

print("Full scorecard:\n", scorecard)
print("\nRohit's Innings2 score    =>", rohit_inn2)
print("Top-2 players, last 2 innings:\n", top2_last2)
print("Dhoni's all innings        =>", dhoni_all)

Full scorecard:
 [[120  45  88]
 [ 99  72 134]
 [ 83  51  67]]

Rohit's Innings2 score    => 45
Top-2 players, last 2 innings:
 [[ 45  88]
 [ 72 134]]
Dhoni's all innings        => [83 51 67]


## 3. Essential Methods: Inspect, Aggregate, Reshape

Once you have an array, you need to:
1. **Inspect** — what are its dimensions, data type, size?
2. **Aggregate** — summarize with sum, mean, max, etc. (optionally along an axis)
3. **Reshape** — rearrange elements without copying data

**Axis intuition (2D):**
- `axis=0` → operate **down the rows** (collapse rows → result per column)
- `axis=1` → operate **across the columns** (collapse columns → result per row)

In [7]:
# 🎓 INSPECT — understand an unknown array before using it
# Imagine you received student data from another team
student_data = np.array([[75.0, 88.5, 92.0],
                          [60.0, 55.5, 73.0],
                          [88.5, 91.0, 95.5]])

print("shape (rows x cols) :", student_data.shape)   # (3, 3)
print("dtype               :", student_data.dtype)   # float64
print("ndim (dimensions)   :", student_data.ndim)    # 2
print("Total elements      :", student_data.size)    # 9

shape (rows x cols) : (3, 3)
dtype               : float64
ndim (dimensions)   : 2
Total elements      : 9


In [8]:
# 🏏 AGGREGATION with axis — Cricket team run matrix
# rows = players (Rohit, Virat, Dhoni), cols = match (M1, M2, M3)
runs = np.array([[45, 80, 55],    # Rohit
                  [30, 90, 120],   # Virat
                  [70, 60,  40]])  # Dhoni

print("Runs matrix:\n", runs)
print("\nTotal runs (all)          =>", runs.sum())                # grand total
print("Match totals (axis=0)     =>", runs.sum(axis=0))           # per MATCH  (collapse players)
print("Player averages (axis=1)  =>", runs.mean(axis=1).round(1)) # per PLAYER (collapse matches)
print("Highest score overall     =>", runs.max())
print("Best match index (flat)   =>", runs.argmax())              # position in flattened array
print("Min score per match       =>", runs.min(axis=0))

Runs matrix:
 [[ 45  80  55]
 [ 30  90 120]
 [ 70  60  40]]

Total runs (all)          => 590
Match totals (axis=0)     => [145 230 215]
Player averages (axis=1)  => [60.  80.  56.7]
Highest score overall     => 120
Best match index (flat)   => 5
Min score per match       => [30 60 40]


In [9]:
# 📸 RESHAPE — imagine pixel data arriving as a flat list
# A 6-pixel image stored as a 1D array → reshape to 2×3 grid
flat_pixels = np.arange(6)          # [0, 1, 2, 3, 4, 5]
image_grid  = flat_pixels.reshape(2, 3)  # 2 rows, 3 columns

describe("flat_pixels", flat_pixels)
describe("image_grid (2×3)", image_grid)

# Use -1 to let NumPy calculate one dimension automatically
auto_reshape = flat_pixels.reshape(-1, 2)   # NumPy figures out 3 rows
describe("auto_reshape (3×2)", auto_reshape)

flat_pixels: shape=(6,), ndim=1, dtype=int64
[0 1 2 3 4 5]

image_grid (2×3): shape=(2, 3), ndim=2, dtype=int64
[[0 1 2]
 [3 4 5]]

auto_reshape (3×2): shape=(3, 2), ndim=2, dtype=int64
[[0 1]
 [2 3]
 [4 5]]



## 4. Common Pitfalls: Views vs Copies, Shape Mismatch

Two tricky areas that trip up beginners:

1. **Views vs Copies**: NumPy slices return a **view** (window into the same data) by default.  
   Modifying the view **modifies the original**!  
   Always use `.copy()` when you want an independent array.

2. **Shape mismatch in broadcasting**: Arrays must be compatible for broadcasting.  
   If shapes don't align, NumPy raises a `ValueError`.

In [10]:
# 🎓 VIEW vs COPY — a real gotcha!
# Suppose we have final grades and a teacher wants to adjust middle students
final_grades = np.array([70, 65, 80, 90, 55])

# View — points to the SAME data in memory
middle_view  = final_grades[1:4]     # grades of students 1, 2, 3
middle_view[:] = 0                   # ⚠️ This ALSO changes final_grades!

# Copy — independent duplicate
bottom_copy  = final_grades[3:5].copy()  # grades of students 3, 4
bottom_copy[:] = 99                      # ✅ This does NOT affect final_grades

print("After view edit, final_grades =>", final_grades)   # Middle ones became 0!
print("middle_view still             =>", middle_view)
print("bottom_copy (independent)     =>", bottom_copy)
print()
print("💡 Rule: Use .copy() when you want to modify a slice without touching the original!")

After view edit, final_grades => [70  0  0  0 55]
middle_view still             => [0 0 0]
bottom_copy (independent)     => [99 99]

💡 Rule: Use .copy() when you want to modify a slice without touching the original!


In [11]:
# 🌡️ SHAPE MISMATCH — know when broadcasting works and when it fails
# Daily temps for 3 cities × 2 days
city_temps = np.zeros((3, 2))

# ✅ WORKS: Add different correction for each of the 2 days (shape (2,) → broadcasts over 3 rows)
day_offset  = np.array([1, 2])
print("Broadcast works (3×2 + (2,)):\n", city_temps + day_offset)

# ❌ FAILS: Trying to add 3 values to a 3×2 array on the wrong axis
city_offset = np.array([1, 2, 3])  # shape (3,) — doesn't align with cols (2)
try:
    city_temps + city_offset
except ValueError as exc:
    print("\nBroadcast fails (3×2 + (3,)) =>", exc)
    print("💡 Fix: Reshape to (3,1) so it broadcasts along columns:",
          (city_temps + city_offset.reshape(3, 1)).shape)

Broadcast works (3×2 + (2,)):
 [[1. 2.]
 [1. 2.]
 [1. 2.]]

Broadcast fails (3×2 + (3,)) => operands could not be broadcast together with shapes (3,2) (3,) 
💡 Fix: Reshape to (3,1) so it broadcasts along columns: (3, 2)
